apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: sharetrip
type: Opaque
stringData:
  DATABASE_DSN: "postgres://postgres:admin@172.17.0.1:6545/notification_db?sslmode=disable"