apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: sharetrip
data:
  KAFKA_BROKERS: "sharetrip-kafka:29092"
  TRIP_EVENTS_TOPIC: "trip.events"
  KAFKA_GROUP_ID: "notification-service"
  SEND_TIMEOUT_MS: "2000"