// Code generated by MockGen. DO NOT EDIT.
// Source: trip_ports.go
//
// Generated by this command:
//
//	mockgen -source=trip_ports.go -destination=mocks/contract_checker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "share_trip/internal/domain"
	outbox "share_trip/internal/outbox"
	service "share_trip/internal/service"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTripRepository is a mock of TripRepository interface.
type MockTripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryMockRecorder
	isgomock struct{}
}

// MockTripRepositoryMockRecorder is the mock recorder for MockTripRepository.
type MockTripRepositoryMockRecorder struct {
	mock *MockTripRepository
}

// NewMockTripRepository creates a new mock instance.
func NewMockTripRepository(ctrl *gomock.Controller) *MockTripRepository {
	mock := &MockTripRepository{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepository) EXPECT() *MockTripRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTripRepository) Create(ctx context.Context, trip domain.Trip, history domain.TripHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, trip, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTripRepositoryMockRecorder) Create(ctx, trip, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTripRepository)(nil).Create), ctx, trip, history)
}

// GetByID mocks base method.
func (m *MockTripRepository) GetByID(ctx context.Context, tripID uuid.UUID) (domain.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, tripID)
	ret0, _ := ret[0].(domain.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTripRepositoryMockRecorder) GetByID(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTripRepository)(nil).GetByID), ctx, tripID)
}

// MockTripRepositoryTx is a mock of TripRepositoryTx interface.
type MockTripRepositoryTx struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryTxMockRecorder
	isgomock struct{}
}

// MockTripRepositoryTxMockRecorder is the mock recorder for MockTripRepositoryTx.
type MockTripRepositoryTxMockRecorder struct {
	mock *MockTripRepositoryTx
}

// NewMockTripRepositoryTx creates a new mock instance.
func NewMockTripRepositoryTx(ctrl *gomock.Controller) *MockTripRepositoryTx {
	mock := &MockTripRepositoryTx{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepositoryTx) EXPECT() *MockTripRepositoryTxMockRecorder {
	return m.recorder
}

// CreateHistory mocks base method.
func (m *MockTripRepositoryTx) CreateHistory(ctx context.Context, history domain.TripHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHistory", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateHistory indicates an expected call of CreateHistory.
func (mr *MockTripRepositoryTxMockRecorder) CreateHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHistory", reflect.TypeOf((*MockTripRepositoryTx)(nil).CreateHistory), ctx, history)
}

// CreateOutboxEvent mocks base method.
func (m *MockTripRepositoryTx) CreateOutboxEvent(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOutboxEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOutboxEvent indicates an expected call of CreateOutboxEvent.
func (mr *MockTripRepositoryTxMockRecorder) CreateOutboxEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOutboxEvent", reflect.TypeOf((*MockTripRepositoryTx)(nil).CreateOutboxEvent), ctx, event)
}

// GetForUpdateByID mocks base method.
func (m *MockTripRepositoryTx) GetForUpdateByID(ctx context.Context, tripID uuid.UUID) (domain.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdateByID", ctx, tripID)
	ret0, _ := ret[0].(domain.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdateByID indicates an expected call of GetForUpdateByID.
func (mr *MockTripRepositoryTxMockRecorder) GetForUpdateByID(ctx, tripID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdateByID", reflect.TypeOf((*MockTripRepositoryTx)(nil).GetForUpdateByID), ctx, tripID)
}

// UpdateStatus mocks base method.
func (m *MockTripRepositoryTx) UpdateStatus(ctx context.Context, tripID uuid.UUID, status domain.TripStatus) (domain.Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tripID, status)
	ret0, _ := ret[0].(domain.Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTripRepositoryTxMockRecorder) UpdateStatus(ctx, tripID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTripRepositoryTx)(nil).UpdateStatus), ctx, tripID, status)
}

// MockContractChecker is a mock of ContractChecker interface.
type MockContractChecker struct {
	ctrl     *gomock.Controller
	recorder *MockContractCheckerMockRecorder
	isgomock struct{}
}

// MockContractCheckerMockRecorder is the mock recorder for MockContractChecker.
type MockContractCheckerMockRecorder struct {
	mock *MockContractChecker
}

// NewMockContractChecker creates a new mock instance.
func NewMockContractChecker(ctrl *gomock.Controller) *MockContractChecker {
	mock := &MockContractChecker{ctrl: ctrl}
	mock.recorder = &MockContractCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractChecker) EXPECT() *MockContractCheckerMockRecorder {
	return m.recorder
}

// CheckService mocks base method.
func (m *MockContractChecker) CheckService(ctx context.Context, driverID, serviceCode string) (service.CheckResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckService", ctx, driverID, serviceCode)
	ret0, _ := ret[0].(service.CheckResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckService indicates an expected call of CheckService.
func (mr *MockContractCheckerMockRecorder) CheckService(ctx, driverID, serviceCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckService", reflect.TypeOf((*MockContractChecker)(nil).CheckService), ctx, driverID, serviceCode)
}
