apiVersion: v1
kind: Secret
metadata:
  name: contract-secret
  namespace: sharetrip
type: Opaque
stringData:
  DATABASE_DSN: "postgres://postgres:admin@172.17.0.1:6544/sharetrip_contract?sslmode=disable"